__default:
  description: |
    P√°gina pessoal do Gabriel Chiconi Lins. Desenvolvedor web full stack de Santos-SP. 
    Escrevo artigos, colaboro em projetos open source e gosto de conversar.
    Sistemas para empresas, cria√ß√£o de websites, consultoria de inform√°tica, open source,
    startups e tutoriais de programa√ß√£o.
  canonical: https://lins.dev
  openGraph:
    title: lins.dev | Gabriel Chiconi Lins
    url: https://lins.dev
    images:
      - url: https://lins.dev/static/me_256.png
        width: 256
        height: 256
        alt: Gabriel Chiconi Lins
      - url: https://lins.dev/static/me.png
        width: 500
        height: 500
        alt: Gabriel Chiconi Lins
    site_name: lins.dev
    profile:
      firstName: Gabriel
      lastName: Chiconi

home:

contact:
  canonical: https://lins.dev/contact
  openGraph:
    url: https://lins.dev/contact

projects:
  description: |
    Projetos do Gabriel Chiconi Lins. üöÄ Desenvolvedor web full stack de Santos-SP. 
    Escrevo artigos, colaboro em projetos open source e gosto de conversar.
    Sistemas para empresas, cria√ß√£o de websites, consultoria de inform√°tica, open source,
    startups e tutoriais de programa√ß√£o.
  canonical: https://lins.dev/projects
  openGraph:
    url: https://lins.dev/projects
